spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: s283945
    password: NksFJHrE5pgQeeWJ
    url: jdbc:postgresql://pg:5432/studs
#    username: postgres
#    password: 123
#    url: jdbc:postgresql://localhost/soa
  jpa:
    generate-ddl: true
server:
  port: 41549